# Generated by Django 6.0.8 on 2026-08-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
